In [1]:
import numpy as np

In [ ]:
liste = np.arange(2,201,2).reshape(10,10)
print(liste)



In [29]:
x=int(input("Lütfen Satır Sayısını giriniz"))
y=int(input("Lütfen Sutun Sayısını giriniz"))



a = np.zeros((x,y))
for i in range(1,x+1):
    a[(i-1),(0)]= 1
    a[(i-1),(y-1)]= 1
for i in range(1,y+1):
    a[(0), (i-1)] = 1
    a[(x-1),(i-1)]= 1
print(a)

Lütfen Satır Sayısını giriniz 3
Lütfen Sutun Sayısını giriniz 4


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
